version: "3.8"
services:
  callweb-api:
    build:
      context: ./docker/callweb-api
    image: callweb-api:latest
    container_name: callweb-api
    ports:
      - "8081:80"
    volumes: #ローカルのソースコードをコンテナにマウント（本番ではDockerfileにCOPYを使った方がいい気がする。）
      - /etc/localtime:/etc/localtime:ro
      - ./html/pl_api_ci4:/var/www/callweb-api
      - ./log/ap:/var/www/callweb-api/log/ap
      - ./log/ap_ex:/var/www/callweb-api/log/ap_ex
    environment:
      - TZ=Asia/Tokyo
    restart: always
    networks:
      - callweb-net

  callweb-spa:
    build:
      context: ./docker/callweb-spa
    image: callweb-spa:latest
    container_name: callweb-spa
    ports:
      - "8080:80"
      - "4200:4200"     

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./html/pl_web:/var/www/callweb-spa
    environment:
      - TZ=Asia/Tokyo
    restart: always
    networks:
      - callweb-net

  link_db: #local mysql
    image: mysql:8.0
    container_name: "link_db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pl_gyodb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - callweb-net

networks:
  callweb-net:
    driver: bridge